
NUMBER_OF_RUNS = 1000

MATCHES_PER_ROBOT = 10
ITERATIONS = 1000 # Iterations of match making

MIN_ACCURACY = 0.50
MAX_ACCURACY = 0.95
MIN_MAGAZINE_SIZE = 20
MAX_MAGAZINE_SIZE = 80

MATCH_ACCURACY_VARIANCE = 0.1
SCOUT_MIN_TIME_ERROR = -0.25
SCOUT_MAX_TIME_ERROR = 0.25
SCOUT_MAGAZINE_ERROR = 0.1 # error margin of the scouter on the magazine percentage metrics

SIMULATION_TIME_STEP = 0.05
MIN_NUMBER_OF_VOLLEYS = 1
MAX_NUMBER_OF_VOLLEYS = 6
MIN_MAGAZINE_FILL_PERCENTAGE = 0.1
MAX_MAGAZINE_FILL_PERCENTAGE = 1.0

RATE_OF_FIRE_JITTER = 1
MAX_TIME_TO_DEPLETE = 1000.0

NOTIFICATION_STEP = 1
